### ISSUE TITLE
Add walkthrough testing on Mac

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/containers#122]
https://github.com/ReproNim/containers/blob/master/.github/workflows/tests.yaml

testing is trivial -- just running

```
bash <(sed -n -e '/^ *#!/,/^```$/p' README.md | grep -v '```')
```
which runs that snippet from README.md with datalad-container -- so just needs installation of git-annex and datalad-container,. likely using datalad-installer.

**Comment by jwodder** [comment]
@yarikoptic I'm unclear what you're asking for.  Do you want the `tests.yaml` workflow to include testing on macOS, or something else?

**Comment by yarikoptic** [comment]
> @yarikoptic I'm unclear what you're asking for. Do you want the `tests.yaml` workflow to include testing on macOS...?

yes

**Comment by yarikoptic** [comment]
odd, I think I saw @jwodder's statement that it is not trivial to add docker support on mac, and then mine that I have tried myself too in https://github.com/yarikoptic/docker-gh-action-test but that did not work out fully (docker did not start) so let's indeed postpone

**Comment by jwodder** [comment]
@yarikoptic Those comments were in my PR: #123
