### ISSUE TITLE
listing of bids apps is being moved to a new repo

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/containers#129]
part of the centralization process of BIDS resources:

the yaml file should keep the same structure but will be in the bids website repo

https://github.com/bids-standard/bids-website/pull/489

this may break some of your workflow so wanted to give you a head up

**Comment by Remi-Gau** [comment]
see also: https://github.com/bids-apps/bids-apps.github.io/pull/150

**Comment by yarikoptic** [comment]
THANK YOU!
