### ISSUE TITLE
MRIQC migration to nipreps: missing latest release

### ISSUE THREAD

**Issue by bpinsard** [ReproNim/containers#71]
It seems that the latest release from nipreps org is not pushed here automagically.

**Comment by yarikoptic** [comment]
logic should be fixed in e7e4db4dc09d2a906179a32fb1630c2a457c8965 , script is running.  If it fails to add mriqc within a day or so (needs to build other containers before then) - let's reopen.

**Comment by yarikoptic** [comment]
notes: I think we are good. We have https://github.com/ReproNim/containers/blob/master/images/bids/bids-mriqc--22.0.1.sing and I had to clean up some space on `/mnt/docker` which hosts tmp location for singularity for conversion to let other images convert fine... reenabled cron job

**Comment by bpinsard** [comment]
Great, thanks!
