### ISSUE TITLE
Rewrite create_singularities in Python

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/containers#73]
The goal is to rewrite bash https://github.com/ReproNim/containers/blob/master/scripts/create_singularities in Python. 

Rationale:
- gain in readability/maintainability
- do not need to be "advanced bash developers" needing to come up with fixes like d79d125b63d87b7560556d315c83df629645da31 
- possibly ease testing of at least some helpers
- if written as async, enjoy parallel execution/creation of containers
- ~~get rid of unused stuff:  there is no longer singularity hub and its API so that code could be gone~~

While working on it, keep in mind upcoming extensions such as #74

**Comment by jwodder** [comment]
@yarikoptic 

> if written as async, enjoy parallel execution/creation of containers

Exactly what actions do you envision being run in parallel?  Would it include the datalad operations (saving etc.)?

> get rid of unused stuff: there is no longer singularity hub and its API so that code could be gone

I don't seem to see anything in the script for interacting with the singularity hub; exactly which parts are currently unused?

**Comment by jwodder** [comment]
@yarikoptic For the "upcoming extension" #74, exactly what would be done for that?  Is it just converting more Docker images to Singularity or something else?

**Comment by yarikoptic** [comment]
yes, I think it would be pretty much the same conversion and just with a different source for getting the listing of those containers.  So may be nothing specific is to be done for that ATM.
