### ISSUE TITLE
Move from travis to github actions

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/containers#98]
I believe travis is defunct.  Let's move the tests in .travis.yml into a github action (also replace badge in README.md)

**Comment by jwodder** [comment]
@yarikoptic There's already [a GitHub Actions test workflow](https://github.com/ReproNim/containers/blob/master/.github/workflows/tests.yaml) in this repository.  What more do you need for this?

**Comment by yarikoptic** [comment]
right -- " Additional tests" - to test README.md.

Keep that one but also make "Tests" with following from travis setup:

```
install:
  - travis_retry ./travis/install.sh

script:
    - grep -m 1 -l '^#!/bin/.*sh' | grep -v '\.\(txt\|md\)' | xargs shellcheck
    - bats -t scripts/tests
 ```

steps

**Comment by jwodder** [comment]
@yarikoptic So you want a separate workflow with a title of "Tests"?  Normally I'd name it `test.yml` or `tests.yml`, but there's already a `tests.yaml` here, so what should the filename be?

**Comment by yarikoptic** [comment]
I don't care much. `base-tests.yml`?
